# Generated by Django 5.2.4 on 2025-09-11 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientuser',
            name='is_tenant_admin',
            field=models.BooleanField(default=False),
        ),
    ]
