# Generated by Django 5.2.4 on 2025-09-11 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_tenantuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantuser',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='app.client'),
        ),
    ]
